# -*- coding: utf-8 -*-
"""Remidial02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tglRAV1dJBsgLRF8CQzOF7SiF1P9WqKh
"""

def hitung_biaya_parkir_terminal(lama_parkir):
  biaya_awal = 3000
  if lama_parkir > 2:
    biaya_tambahan = (lama_parkir - 2) * 1500
  else:
    biaya_tambahan = 0

  if lama_parkir > 24:
    biaya_tambahan += 10000

  total_biaya = biaya_awal + biaya_tambahan
  return total_biaya

# Contoh penggunaan
lama_parkir = int(input("Masukkan lama parkir (jam): "))

biaya = hitung_biaya_parkir_terminal(lama_parkir)
print("Total biaya parkir:", biaya)